<?php 
/**
 * Displays the CSS generated by the customizer.
 *
 * @package       Tube Ace
 * @subpackage    Play
 * @since         Play 1.0
 * @link          http://tubeace.com
 */
?>

<?php 

self::generate_css('body', 'background-color', 'background_color', '#'); // added theme support 

/* Header */
// Site Title
if(get_theme_mod('header_show_site_title', $tubeaceplay_customizer_defaults['header_show_site_title'])==1){
	self::generate_css('#site-title', 'font-family', 'header_site_title_font_family');
	self::font_css('#site-title', 'header_site_title_font');
	self::generate_css('#site-title', 'color', 'header_site_title_color');
}
// Tagline
if(get_theme_mod('header_show_tagline', $tubeaceplay_customizer_defaults['header_show_tagline'])==1){
	self::generate_css('#tagline', 'font-family', 'header_tagline_font_family');
	self::generate_css('#tagline', 'color', 'header_tagline_color');
	self::font_css('#tagline', 'header_tagline_font');
}
// Search Form
if(get_theme_mod('header_show_search', $tubeaceplay_customizer_defaults['header_show_search'])==1){
	self::generate_css('#search-form input', 'background-color', 'header_search_input_color');
	self::generate_css('#search-form input', 'color', 'header_search_txt_color');
	self::generate_css('#search-form input', 'border-color', 'header_search_border_color');
	self::generate_css('#search-form button', 'background-color', 'header_search_button_color');
	self::generate_css('#search-form button', 'color', 'header_search_button_txt_color');
	self::generate_css('#search-form button', 'border-color', 'header_search_button_border_color');
}
// Main
if(get_theme_mod('header_transparent_bg', $tubeaceplay_customizer_defaults['header_transparent_bg'])==false) { self::generate_css('#header', 'background-color', 'header_bg_color'); } else { self::transparent_css('#header'); };
self::generate_css('#header', 'font-family', 'header_font_family');
self::font_css('#header', 'header_font');
self::generate_css('#header', 'color', 'header_txt_color');
self::generate_css('.navbar a', 'color', 'header_link_color');
self::generate_css('#header', 'border-color', 'header_border_color');

/* Navbar */
// Main
if(get_theme_mod('navbar_transparent_bg', $tubeaceplay_customizer_defaults['navbar_transparent_bg'])==false) { self::generate_css('#navbar-block', 'background-color', 'navbar_bg_color'); } else { self::transparent_css('#navbar-block'); };
if(get_theme_mod('navbar_item_transparent_bg', $tubeaceplay_customizer_defaults['navbar_item_transparent_bg'])==false) { self::generate_css('#navbar-block > ul > li:not(.current_page_item):not(.current-menu-item) > a, #header-menu ul .menu-item:not(.current_page_item):not(.current-menu-item) a', 'background-color', 'navbar_item_bg_color'); } else { self::transparent_css('#navbar-block > ul > li:not(.current_page_item):not(.current-menu-item) > a, #header-menu ul .menu-item:not(.current_page_item):not(.current-menu-item) a'); };
self::generate_css('#navbar ul li a', 'font-family', 'navbar_font_family');
self::font_css('#navbar ul li a', 'navbar_font');
self::generate_css('#navbar ul li a', 'color', 'navbar_txt_color');
self::generate_css('#navbar ul li a', 'border-color', 'navbar_border_color');
// Hover
if(get_theme_mod('navbar_hover_transparent_bg', $tubeaceplay_customizer_defaults['navbar_hover_transparent_bg'])==false) { self::generate_css('#navbar-block > ul > li:not(.current_page_item):not(.current-menu-item) > a:hover, #header-menu ul .menu-item:not(.current_page_item):not(.current-menu-item) a:hover', 'background-color', 'navbar_hover_bg_color'); } else { self::transparent_css('#navbar-block > ul > li:not(.current_page_item):not(.current-menu-item) > a:hover, #header-menu ul .menu-item:not(.current_page_item):not(.current-menu-item) a:hover'); };
self::generate_css('#navbar-block > ul > li:not(.current_page_item):not(.current-menu-item) > a:hover, #header-menu ul .menu-item:not(.current_page_item):not(.current-menu-item) a:hover', 'color', 'navbar_hover_txt_color');
self::generate_css('#navbar-block > ul > li:not(.current_page_item):not(.current-menu-item) > a:hover, #header-menu ul .menu-item:not(.current_page_item):not(.current-menu-item) a:hover', 'border-color', 'navbar_hover_border_color');
// Current
if(get_theme_mod('navbar_current_transparent_bg', $tubeaceplay_customizer_defaults['navbar_current_transparent_bg'])==false) { self::generate_css('#navbar .current_page_item a, #navbar ul li .current_page_item a, #navbar .current-menu-item a', 'background-color', 'navbar_current_bg_color'); } else { self::transparent_css('#navbar .current_page_item a, #navbar ul li .current_page_item a, #navbar .current-menu-item a'); };
self::generate_css('#navbar .current_page_item > a, #navbar .current-menu-item > a', 'color', 'navbar_current_txt_color');
self::generate_css('#navbar .current_page_item > a, #navbar .current-menu-item > a', 'border-color', 'navbar_current_border_color');

/* Header Widget Menu */
self::generate_css('.header-widget-title', 'color', 'header_widget_menu_title_color');
self::generate_css('.header-widget-title', 'font-family', 'header_widget_menu_title_font_family');
self::font_css('.header-widget-title', 'header_widget_menu_title_font');
if(get_theme_mod('header_widget_menu_transparent_bg', $tubeaceplay_customizer_defaults['header_widget_menu_transparent_bg'])==false) { self::generate_css('.header-widget-area ul', 'background-color', 'header_widget_menu_bg_color'); } else { self::transparent_css('.header-widget-area ul'); };
if(get_theme_mod('header_widget_menu_item_transparent_bg', $tubeaceplay_customizer_defaults['header_widget_menu_item_transparent_bg'])==false) { self::generate_css('.header-widget-area ul li a', 'background-color', 'header_widget_menu_item_bg_color'); } else { self::transparent_css('.header-widget-area ul li a'); };
self::generate_css('.header-widget-area ul li a', 'font-family', 'header_widget_menu_font_family');
self::font_css('.header-widget-area ul li a', 'header_widget_menu_font');
self::generate_css('.header-widget-area ul li a', 'color', 'header_widget_menu_txt_color');
self::generate_css('.header-widget-area ul li a', 'border-color', 'header_widget_menu_border_color');
if(get_theme_mod('header_widget_menu_hover_transparent_bg', $tubeaceplay_customizer_defaults['header_widget_menu_hover_transparent_bg'])==false) { self::generate_css('.header-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'background-color', 'header_widget_menu_hover_bg_color'); } else { self::transparent_css('.header-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover'); };
self::generate_css('.header-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'color', 'header_widget_menu_hover_txt_color');
self::generate_css('.header-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'border-color', 'header_widget_menu_hover_border_color');
if(get_theme_mod('header_widget_menu_current_transparent_bg', $tubeaceplay_customizer_defaults['header_widget_menu_current_transparent_bg'])==false) { self::generate_css('.header-widget-area .current_page_item > a, .header-widget-area .current-cat > a', 'background-color', 'header_widget_menu_current_bg_color'); } else { self::transparent_css('.header-widget-area .current_page_item > a, .header-widget-area .current-cat > a'); };
self::generate_css('.header-widget-area .current_page_item > a, .header-widget-area .current-cat > a', 'color', 'header_widget_menu_current_txt_color');
self::generate_css('.header-widget-area .current_page_item > a, .header-widget-area .current-cat > a', 'border-color', 'header_widget_menu_current_border_color');

/* Content Area */
if(get_theme_mod('content_transparent_bg', $tubeaceplay_customizer_defaults['content_transparent_bg'])==false) { self::generate_css('#content', 'background-color', 'content_bg_color'); } else { self::transparent_css('#content'); };
self::generate_css('#content', 'border-color', 'content_border_color');

/* Left Sidebar */
if(get_theme_mod('left_sidebar_transparent_bg', $tubeaceplay_customizer_defaults['left_sidebar_transparent_bg'])==false){ self::generate_css('.sidebar-left', 'background-color', 'left_sidebar_bg_color'); } else { self::transparent_css('.sidebar-left'); };
self::generate_css('.sidebar-left', 'font-family', 'left_sidebar_font_family');
self::font_css('.sidebar-left', 'left_sidebar_font');
self::generate_css('.sidebar-left', 'color', 'left_sidebar_txt_color');
self::generate_css('.sidebar-left a', 'color', 'left_sidebar_link_color');
self::generate_css('.sidebar-left', 'border-color', 'left_sidebar_border_color');

/* Left Sidebar Widget Menu */
// Title
self::generate_css('.sidebar-left-widget-title', 'color', 'left_sidebar_widget_menu_title_color');
self::generate_css('.sidebar-left-widget-title', 'font-family', 'left_sidebar_widget_menu_title_font_family');
self::font_css('.sidebar-left-widget-title', 'left_sidebar_widget_menu_title_font');
// Main
if(get_theme_mod('left_sidebar_widget_menu_transparent_bg', $tubeaceplay_customizer_defaults['left_sidebar_widget_menu_transparent_bg'])==false){ self::generate_css('.sidebar-left-widget-area ul', 'background-color', 'left_sidebar_widget_menu_bg_color'); } else { self::transparent_css('.sidebar-left-widget-area ul'); };
if(get_theme_mod('left_sidebar_widget_menu_item_transparent_bg', $tubeaceplay_customizer_defaults['left_sidebar_widget_menu_item_transparent_bg'])==false){ self::generate_css('.sidebar-left-widget-area ul li a', 'background-color', 'left_sidebar_widget_menu_item_bg_color'); } else { self::transparent_css('.sidebar-left-widget-area ul li a'); };
self::generate_css('.sidebar-left-widget-area ul li', 'font-family', 'left_sidebar_widget_menu_font_family');
self::font_css('.sidebar-left-widget-area ul li a', 'left_sidebar_widget_menu_font');
self::generate_css('.sidebar-left-widget-area ul li a', 'color', 'left_sidebar_widget_menu_txt_color');
self::generate_css('.sidebar-left-widget-area ul li a', 'border-color', 'left_sidebar_widget_menu_border_color');
// Hover
if(get_theme_mod('left_sidebar_widget_menu_hover_transparent_bg', $tubeaceplay_customizer_defaults['left_sidebar_widget_menu_hover_transparent_bg'])==false){ self::generate_css('.sidebar-left-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'background-color', 'left_sidebar_widget_menu_hover_bg_color'); } else { self::transparent_css('.sidebar-left-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover'); };
self::generate_css('.sidebar-left-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'color', 'left_sidebar_widget_menu_hover_txt_color');
self::generate_css('.sidebar-left-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'border-color', 'left_sidebar_widget_menu_hover_border_color');
// Current
if(get_theme_mod('left_sidebar_widget_menu_current_transparent_bg', $tubeaceplay_customizer_defaults['left_sidebar_widget_menu_current_transparent_bg'])==false){ self::generate_css('.sidebar-left-widget-area .current_page_item > a, .sidebar-left-widget-area .current-cat > a', 'background-color', 'left_sidebar_widget_menu_current_bg_color'); } else { self::transparent_css('.sidebar-left-widget-area .current_page_item > a, .sidebar-left-widget-area .current-cat > a'); };
self::generate_css('.sidebar-left-widget-area .current_page_item > a, .sidebar-left-widget-area .current-cat > a', 'color', 'left_sidebar_widget_menu_current_txt_color');
self::generate_css('.sidebar-left-widget-area .current_page_item > a, .sidebar-left-widget-area .current-cat > a', 'border-color', 'left_sidebar_widget_menu_current_border_color');
 
/* Right Sidebar */
if(get_theme_mod('right_sidebar_transparent_bg', $tubeaceplay_customizer_defaults['right_sidebar_transparent_bg'])==false){ self::generate_css('.sidebar-right', 'background-color', 'right_sidebar_bg_color'); } else { self::transparent_css('.sidebar-right'); };
self::generate_css('.sidebar-right', 'color', 'right_sidebar_txt_color');
self::generate_css('.sidebar-right', 'font-family', 'right_sidebar_font_family');
self::font_css('.sidebar-right', 'right_sidebar_font');
self::generate_css('.sidebar-right a', 'color', 'right_sidebar_link_color');
self::generate_css('.sidebar-right', 'border-color', 'right_sidebar_border_color');

/* Right Sidebar Widget Menu */
// Title
self::generate_css('.sidebar-right-widget-title', 'color', 'right_sidebar_widget_menu_title_color');
self::generate_css('.sidebar-right-widget-title', 'font-family', 'right_sidebar_widget_menu_title_font_family');
self::font_css('.sidebar-right-widget-title', 'right_sidebar_widget_menu_title_font');
// Main
if(get_theme_mod('right_sidebar_widget_menu_transparent_bg', $tubeaceplay_customizer_defaults['right_sidebar_widget_menu_transparent_bg'])==false){ self::generate_css('.sidebar-right-widget-area ul', 'background-color', 'right_sidebar_widget_menu_bg_color'); } else { self::transparent_css('.sidebar-right-widget-area ul'); };
if(get_theme_mod('right_sidebar_widget_menu_item_transparent_bg', $tubeaceplay_customizer_defaults['right_sidebar_widget_menu_item_transparent_bg'])==false){ self::generate_css('.sidebar-right-widget-area ul li a', 'background-color', 'right_sidebar_widget_menu_item_bg_color'); } else { self::transparent_css('.sidebar-right-widget-area ul li a'); };
self::generate_css('.sidebar-right-widget-area ul li', 'font-family', 'right_sidebar_widget_menu_font_family');
self::font_css('.sidebar-right-widget-area ul li a', 'right_sidebar_widget_menu_font');
self::generate_css('.sidebar-right-widget-area ul li a', 'color', 'right_sidebar_widget_menu_txt_color');
self::generate_css('.sidebar-right-widget-area ul li a', 'border-color', 'right_sidebar_widget_menu_border_color');
// Hover
if(get_theme_mod('right_sidebar_widget_menu_hover_transparent_bg', $tubeaceplay_customizer_defaults['right_sidebar_widget_menu_hover_transparent_bg'])==false){ self::generate_css('.sidebar-right-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'background-color', 'right_sidebar_widget_menu_hover_bg_color'); } else { self::transparent_css('.sidebar-right-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover'); };
self::generate_css('.sidebar-right-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'color', 'right_sidebar_widget_menu_hover_txt_color');
self::generate_css('.sidebar-right-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'border-color', 'right_sidebar_widget_menu_hover_border_color');
// Current
if(get_theme_mod('right_sidebar_widget_menu_current_transparent_bg', $tubeaceplay_customizer_defaults['right_sidebar_widget_menu_current_transparent_bg'])==false){ self::generate_css('.sidebar-right-widget-area .current_page_item > a, .sidebar-right-widget-area .current-cat > a', 'background-color', 'right_sidebar_widget_menu_current_bg_color'); } else { self::transparent_css('.sidebar-right-widget-area .current_page_item > a, .sidebar-right-widget-area .current-cat > a'); };
self::generate_css('.sidebar-right-widget-area .current_page_item > a, .sidebar-right-widget-area .current-cat > a', 'color', 'right_sidebar_widget_menu_current_txt_color');
self::generate_css('.sidebar-right-widget-area .current_page_item > a, .sidebar-right-widget-area .current-cat > a', 'border-color', 'right_sidebar_widget_menu_current_border_color');

/* Post Preview */
self::generate_css('#tubeace-results a.preview-title', 'font-family', 'preview_title_font_family');
self::font_css('#tubeace-results a.preview-title', 'preview_title_font');
self::generate_css('#tubeace-results a.preview-title', 'color', 'preview_title_txt_color');
if(get_theme_mod('preview_transparent_bg', $tubeaceplay_customizer_defaults['preview_transparent_bg'])==false) { self::generate_css('#tubeace-results .post-preview-styling', 'background-color', 'preview_bg_color'); } else { self::transparent_css('#tubeace-results .post-preview-styling'); };
self::generate_css('#tubeace-results .post-preview-styling', 'font-family', 'preview_font_family');
self::font_css('#tubeace-results .post-preview-styling', 'preview_font');
self::generate_css('#tubeace-results .post-preview-styling', 'color', 'preview_txt_color');
self::generate_css('#tubeace-results .post-preview-styling:not(.sticky) :not(.post-preview-tags):not(.post-preview-category):not(.post-preview-performers):not(.preview-date) a:not(.preview-title):not(.preview-date), #tubeace-results a.post-edit-link', 'color', 'preview_link_color');
self::generate_css('#tubeace-results .post-preview-styling', 'border-color', 'preview_border_color');
self::generate_css('#tubeace-results .wp-post-image', 'border-color', 'preview_featured_image_border_color');

if(get_theme_mod('preview_duration_transparent_bg', $tubeaceplay_customizer_defaults['preview_duration_transparent_bg'])==false) { self::generate_css('#tubeace-results .post-preview-styling .duration', 'background-color', 'preview_duration_bg_color'); } else { self::transparent_css('#tubeace-results .post-preview-styling .duration'); };
self::generate_css('#tubeace-results .post-preview-styling .duration', 'color', 'preview_duration_txt_color');
self::generate_css('#tubeace-results .post-preview-styling .duration', 'font-family', 'preview_duration_font_family');
self::font_css('#tubeace-results .post-preview-styling .duration', 'preview_duration_font');
self::generate_css('#tubeace-results .post-preview-styling .duration', 'border-color', 'preview_duration_border_color');

self::generate_css('#tubeace-results .preview-date > a, .preview-date', 'color', 'preview_post_date_txt_color');
self::generate_css('#tubeace-results .post-preview-tags', 'color', 'preview_tags_label_color');
self::generate_css('#tubeace-results .post-preview-tags > a', 'color', 'preview_tags_txt_color');
self::generate_css('#tubeace-results .post-preview-tags', 'font-family', 'preview_tags_font_family');
self::font_css('#tubeace-results .post-preview-tags', 'preview_tags_font');
if(get_theme_mod('preview_tags_transparent_bg', $tubeaceplay_customizer_defaults['preview_tags_transparent_bg'])==false) { self::generate_css('#tubeace-results .post-preview-tags > a', 'background-color', 'preview_tags_bg_color'); } else { self::transparent_css('#tubeace-results .post-preview-tags > a'); };
self::generate_css('#tubeace-results .post-preview-tags > a', 'border-color', 'preview_tags_border_color');
self::generate_css('#tubeace-results .post-preview-category', 'color', 'preview_category_label_color');
self::generate_css('#tubeace-results .post-preview-category > a', 'color', 'preview_category_txt_color');
self::generate_css('#tubeace-results .post-preview-category', 'font-family', 'preview_category_font_family');
self::font_css('#tubeace-results .post-preview-category', 'preview_category_font');
if(get_theme_mod('preview_category_transparent_bg', $tubeaceplay_customizer_defaults['preview_category_transparent_bg'])==false) { self::generate_css('#tubeace-results .post-preview-category > a', 'background-color', 'preview_category_bg_color'); } else { self::transparent_css('#tubeace-results .post-preview-category > a'); };
self::generate_css('#tubeace-results .post-preview-category > a', 'border-color', 'preview_category_border_color');
self::generate_css('#tubeace-results .post-preview-performers', 'color', 'preview_performers_label_color');
self::generate_css('#tubeace-results .post-preview-performers > a', 'color', 'preview_performers_txt_color');
self::generate_css('#tubeace-results .post-preview-performers', 'font-family', 'preview_performers_font_family');
self::font_css('#tubeace-results .post-preview-performers', 'preview_performers_font');
if(get_theme_mod('preview_performers_transparent_bg', $tubeaceplay_customizer_defaults['preview_performers_transparent_bg'])==false) { self::generate_css('#tubeace-results .post-preview-performers > a', 'background-color', 'preview_performers_bg_color'); } else { self::transparent_css('#tubeace-results .post-preview-performers > a'); };
self::generate_css('#tubeace-results .post-preview-performers > a', 'border-color', 'preview_performers_border_color');
self::generate_css('#tubeace-results .post-preview-view-count', 'color', 'preview_view_count_txt_color');
self::generate_css('#tubeace-results .post-preview-view-count', 'font-family', 'preview_view_count_font_family');
self::font_css('#tubeace-results .post-preview-view-count', 'preview_view_count_font');
self::generate_css('#tubeace-results .post-preview-rating', 'color', 'preview_rating_txt_color');
self::generate_css('#tubeace-results .post-preview-rating', 'font-family', 'preview_rating_font_family');
self::font_css('#tubeace-results .post-preview-rating', 'preview_rating_font');


/* Sticky Post Preview */
self::generate_css('#tubeace-results .sticky .ribbon span', 'color', 'sticky_preview_label_txt_color');
self::generate_css('#tubeace-results .sticky .ribbon span', 'background-color', 'sticky_preview_label_bg_color');
self::generate_css('#tubeace-results .sticky .ribbon span', 'font-family', 'sticky_preview_label_font_family');
self::font_css('#tubeace-results .sticky .ribbon span', 'sticky_preview_label_font');
self::generate_css('#tubeace-results .sticky a.preview-title', 'font-family', 'sticky_preview_title_font_family');
self::font_css('#tubeace-results .sticky a.preview-title', 'sticky_preview_title_font');
self::generate_css('#tubeace-results .sticky a.preview-title', 'color', 'sticky_preview_title_txt_color');
if(get_theme_mod('sticky_preview_transparent_bg', $tubeaceplay_customizer_defaults['sticky_preview_transparent_bg'])==false) { self::generate_css('#tubeace-results .sticky-post-preview-styling', 'background-color', 'sticky_preview_bg_color'); } else { self::transparent_css('#tubeace-results .sticky-post-preview-styling'); };
self::generate_css('#tubeace-results .sticky', 'font-family', 'sticky_preview_font_family');
self::font_css('#tubeace-results .sticky', 'sticky_preview_font');
self::generate_css('#tubeace-results .sticky', 'color', 'sticky_preview_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-styling :not(.sticky-post-preview-category):not(.sticky-post-preview-tags):not(.sticky-post-preview-performers):not(.sticky-preview-date) a:not(.preview-title):not(.sticky-preview-date), .sticky a.post-edit-link', 'color', 'sticky_preview_link_color');
self::generate_css('#tubeace-results .sticky-post-preview-styling', 'border-color', 'sticky_preview_border_color');
self::generate_css('#tubeace-results .sticky .wp-post-image', 'border-color', 'sticky_preview_featured_image_border_color');

if(get_theme_mod('sticky_preview_duration_transparent_bg', $tubeaceplay_customizer_defaults['sticky_preview_duration_transparent_bg'])==false) { self::generate_css('#tubeace-results .sticky-post-preview-styling .duration', 'background-color', 'sticky_preview_duration_bg_color'); } else { self::transparent_css('#tubeace-results .sticky-post-preview-styling .duration'); };
self::generate_css('#tubeace-results .sticky-post-preview-styling .duration', 'color', 'sticky_preview_duration_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-styling .duration', 'font-family', 'sticky_preview_duration_font_family');
self::font_css('#tubeace-results .sticky-post-preview-styling .duration', 'sticky_preview_duration_font');
self::generate_css('#tubeace-results .sticky-post-preview-styling .duration', 'border-color', 'sticky_preview_duration_border_color');

self::generate_css('#tubeace-results .sticky .sticky-preview-date > a, .sticky .sticky-preview-date', 'color', 'sticky_preview_post_date_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-tags', 'color', 'sticky_preview_tags_label_color');
self::generate_css('#tubeace-results .sticky-post-preview-tags > a', 'color', 'sticky_preview_tags_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-tags', 'font-family', 'sticky_preview_tags_font_family');
self::font_css('#tubeace-results .sticky-post-preview-tags', 'sticky_preview_tags_font');
if(get_theme_mod('sticky_preview_tags_transparent_bg', $tubeaceplay_customizer_defaults['sticky_preview_tags_transparent_bg'])==false) { self::generate_css('#tubeace-results .sticky-post-preview-tags > a', 'background-color', 'sticky_preview_tags_bg_color'); } else { self::transparent_css('#tubeace-results .sticky-post-preview-tags > a'); };
self::generate_css('#tubeace-results .sticky-post-preview-tags > a', 'border-color', 'sticky_preview_tags_border_color');
self::generate_css('#tubeace-results .sticky-post-preview-category', 'color', 'sticky_preview_category_label_color');
self::generate_css('#tubeace-results .sticky-post-preview-category > a', 'color', 'sticky_preview_category_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-category', 'font-family', 'sticky_preview_category_font_family');
self::font_css('#tubeace-results .sticky-post-preview-category', 'sticky_preview_category_font');
if(get_theme_mod('sticky_preview_category_transparent_bg', $tubeaceplay_customizer_defaults['sticky_preview_category_transparent_bg'])==false) { self::generate_css('#tubeace-results .sticky-post-preview-category > a', 'background-color', 'sticky_preview_category_bg_color'); } else { self::transparent_css('#tubeace-results .sticky-post-preview-category > a'); };
self::generate_css('#tubeace-results .sticky-post-preview-category > a', 'border-color', 'sticky_preview_category_border_color');
self::generate_css('#tubeace-results .sticky-post-preview-performers', 'color', 'sticky_preview_performers_label_color');
self::generate_css('#tubeace-results .sticky-post-preview-performers > a', 'color', 'sticky_preview_performers_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-performers', 'font-family', 'sticky_preview_performers_font_family');
self::font_css('#tubeace-results .sticky-post-preview-performers', 'sticky_preview_performers_font');
if(get_theme_mod('sticky_preview_performers_transparent_bg', $tubeaceplay_customizer_defaults['sticky_preview_performers_transparent_bg'])==false) { self::generate_css('#tubeace-results .sticky-post-preview-performers > a', 'background-color', 'sticky_preview_performers_bg_color'); } else { self::transparent_css('#tubeace-results .sticky-post-preview-performers > a'); };
self::generate_css('#tubeace-results .sticky-post-preview-performers > a', 'border-color', 'sticky_preview_performers_border_color');
self::generate_css('#tubeace-results .sticky-post-preview-view-count', 'color', 'sticky_preview_view_count_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-view-count', 'font-family', 'sticky_preview_view_count_font_family');
self::font_css('#tubeace-results .sticky-post-preview-view-count', 'sticky_preview_view_count_font');
self::generate_css('#tubeace-results .sticky-post-preview-rating', 'color', 'sticky_preview_rating_txt_color');
self::generate_css('#tubeace-results .sticky-post-preview-rating', 'font-family', 'sticky_preview_rating_font_family');
self::font_css('#tubeace-results .sticky-post-preview-rating', 'sticky_preview_rating_font');

/* Comments */
if( is_single() || is_attachment() || is_page() ){
	if(get_theme_mod('comments_area_transparent_bg', $tubeaceplay_customizer_defaults['comments_area_transparent_bg'])==false) { self::generate_css('#comments', 'background-color', 'comments_area_bg_color'); } else { self::transparent_css('#comments'); };
	self::generate_css('#comments', 'font-family', 'comments_area_font_family');
	self::font_css('#comments', 'comments_area_font');
	self::generate_css('#comments', 'color', 'comments_area_txt_color');
	self::generate_css('#comments .logged-in-as a', 'color', 'comments_area_link_color');
	self::generate_css('#comments', 'border-color', 'comments_area_border_color');
	if(get_theme_mod('comment_item_transparent_bg', $tubeaceplay_customizer_defaults['comment_item_transparent_bg'])==false) { self::generate_css('.comment', 'background-color', 'comment_item_bg_color'); } else { self::transparent_css('.comment'); };
	self::generate_css('.comment', 'font-family', 'comment_item_font_family');
	self::font_css('.comment', 'comment_item_font');
	self::generate_css('.comment', 'color', 'comment_item_txt_color');
	self::generate_css('.comment a', 'color', 'comment_item_link_color');
	self::generate_css('.comment', 'border-color', 'comment_item_border_color');
	if(get_theme_mod('comment_reply_transparent_bg', $tubeaceplay_customizer_defaults['comment_reply_transparent_bg'])==false) { self::generate_css('.comment-reply', 'background-color', 'comment_reply_bg_color'); } else { self::transparent_css('.comment-reply'); };
	self::generate_css('.comment-reply', 'font-family', 'comment_reply_font_family');
	self::font_css('.comment-reply', 'comment_reply_font');
	self::generate_css('.comment-reply', 'color', 'comment_reply_txt_color');
	self::generate_css('.comment-reply a', 'color', 'comment_reply_link_color');
	self::generate_css('.comment-reply', 'border-color', 'comment_reply_border_color');
	self::generate_css('textarea#comment, #commentform input', 'background-color', 'comment_form_input_bg_color');
	self::generate_css('textarea#comment, #commentform input', 'font-family', 'comment_form_input_font_family');
	self::font_css('textarea#comment, #commentform input', 'comment_form_input_font');
	self::generate_css('textarea#comment, #commentform input', 'color', 'comment_form_input_txt_color');
	self::generate_css('textarea#comment, #commentform input', 'border-color', 'comment_form_input_border_color');
	self::generate_css('#commentform > p > #submit', 'background-color', 'comment_submit_bg_color');
	self::generate_css('#commentform > p > #submit', 'font-family', 'comment_submit_font_family');
	self::font_css('#commentform > p > #submit', 'comment_submit_font');
	self::generate_css('#commentform > p > #submit', 'color', 'comment_submit_txt_color');
	self::generate_css('#commentform > p > #submit', 'border-color', 'comment_submit_border_color');
}

/* Pagination */
if(get_theme_mod('pagination_prev_transparent_bg', $tubeaceplay_customizer_defaults['pagination_prev_transparent_bg'])==false) { self::generate_css('.nav-links a.prev', 'background-color', 'pagination_prev_bg_color'); } else { self::transparent_css('.nav-links a.prev'); };
self::generate_css('.nav-links a.prev', 'font-family', 'pagination_prev_font_family');
self::font_css('.nav-links a.prev', 'pagination_prev_font');
self::generate_css('#tubeace-pagination .nav-links > a.prev', 'color', 'pagination_prev_txt_color');
self::generate_css('#tubeace-pagination a.prev', 'border-color', 'pagination_prev_border_color');

if(get_theme_mod('pagination_current_transparent_bg', $tubeaceplay_customizer_defaults['pagination_current_transparent_bg'])==false) { self::generate_css('.nav-links span.current:not(.prev):not(.next)', 'background-color', 'pagination_current_bg_color'); } else { self::transparent_css('.nav-links span.current:not(.prev):not(.next)'); };
self::generate_css('.nav-links span.current:not(.prev):not(.next)', 'font-family', 'pagination_current_font_family');
self::font_css('.nav-links span.current:not(.prev):not(.next)', 'pagination_current_font');
self::generate_css('#tubeace-pagination .nav-links > span.current:not(.prev):not(.next)', 'color', 'pagination_current_txt_color');
self::generate_css('#tubeace-pagination span.current:not(.prev):not(.next)', 'border-color', 'pagination_current_border_color');

if(get_theme_mod('pagination_num_transparent_bg', $tubeaceplay_customizer_defaults['pagination_num_transparent_bg'])==false) { self::generate_css('.nav-links a.page-numbers:not(.prev):not(.next)', 'background-color', 'pagination_num_bg_color'); } else { self::transparent_css('.nav-links a.page-numbers:not(.prev):not(.next)'); };
self::generate_css('.nav-links a.page-numbers:not(.prev):not(.next)', 'font-family', 'pagination_num_font_family');
self::font_css('.nav-links a.page-numbers:not(.prev):not(.next)', 'pagination_num_font');
self::generate_css('#tubeace-pagination .nav-links > a.page-numbers:not(.prev):not(.next)', 'color', 'pagination_num_txt_color');
self::generate_css('#tubeace-pagination a.page-numbers:not(.prev):not(.next)', 'border-color', 'pagination_num_border_color');

if(get_theme_mod('pagination_num_hover_transparent_bg', $tubeaceplay_customizer_defaults['pagination_num_hover_transparent_bg'])==false) { self::generate_css('.nav-links a.page-numbers:hover:not(.prev):not(.next)', 'background-color', 'pagination_num_hover_bg_color'); } else { self::transparent_css('.nav-links a.page-numbers:hover:not(.prev):not(.next)'); };
self::generate_css('.nav-links a.page-numbers:hover:not(.prev):not(.next)', 'font-family', 'pagination_num_hover_font_family');
self::font_css('.nav-links a.page-numbers:hover:not(.prev):not(.next)', 'pagination_num_hover_font');
self::generate_css('#tubeace-pagination .nav-links > a.page-numbers:hover:not(.prev):not(.next)', 'color', 'pagination_num_hover_txt_color');
self::generate_css('#tubeace-pagination a.page-numbers:hover:not(.prev):not(.next)', 'border-color', 'pagination_num_hover_border_color');

if(get_theme_mod('pagination_dots_transparent_bg', $tubeaceplay_customizer_defaults['pagination_dots_transparent_bg'])==false) { self::generate_css('.nav-links span.dots:not(.prev):not(.next)', 'background-color', 'pagination_dots_bg_color'); } else { self::transparent_css('.nav-links span.dots:not(.prev):not(.next)'); };
self::generate_css('.nav-links span.dots:not(.prev):not(.next)', 'font-family', 'pagination_dots_font_family');
self::font_css('.nav-links span.dots:not(.prev):not(.next)', 'pagination_dots_font');
self::generate_css('#tubeace-pagination .nav-links > span.dots:not(.prev):not(.next)', 'color', 'pagination_dots_txt_color');
self::generate_css('#tubeace-pagination span.dots:not(.prev):not(.next)', 'border-color', 'pagination_dots_border_color');

if(get_theme_mod('pagination_next_transparent_bg', $tubeaceplay_customizer_defaults['pagination_next_transparent_bg'])==false) { self::generate_css('.nav-links a.next', 'background-color', 'pagination_next_bg_color'); } else { self::transparent_css('.nav-links a.next'); };
self::generate_css('#tubeace-pagination .nav-links > a.next', 'font-family', 'pagination_next_font_family');
self::font_css('#tubeace-pagination .nav-links > a.next', 'pagination_next_font');
self::generate_css('#tubeace-pagination .nav-links > a.next', 'color', 'pagination_next_txt_color');
self::generate_css('#tubeace-pagination a.next', 'border-color', 'pagination_next_border_color');

/* Footer */
if(get_theme_mod('footer_transparent_bg', $tubeaceplay_customizer_defaults['footer_transparent_bg'])==false) { self::generate_css('#footer', 'background-color', 'footer_bg_color'); } else { self::transparent_css('#footer'); };
self::generate_css('.footer', 'color', 'footer_txt_color');
self::generate_css('.footer', 'font-family', 'footer_font_family');
self::font_css('.footer', 'footer_font');
self::generate_css('.footer a', 'color', 'footer_link_color');
self::generate_css('#footer', 'border-color', 'footer_border_color');

/* Footer Widget Menu */
// Title
self::generate_css('.footer-widget-title', 'color', 'footer_widget_menu_title_color');
self::generate_css('.footer-widget-title', 'font-family', 'footer_widget_menu_title_font_family');
self::font_css('.footer-widget-title', 'footer_widget_menu_title_font');
// Main
if(get_theme_mod('footer_widget_menu_transparent_bg', $tubeaceplay_customizer_defaults['footer_widget_menu_transparent_bg'])==false){ self::generate_css('.footer-widget-area ul', 'background-color', 'footer_widget_menu_bg_color'); } else { self::transparent_css('.footer-widget-area ul'); };
if(get_theme_mod('footer_widget_menu_item_transparent_bg', $tubeaceplay_customizer_defaults['footer_widget_menu_item_transparent_bg'])==false){ self::generate_css('.footer-widget-area ul li a', 'background-color', 'footer_widget_menu_item_bg_color'); } else { self::transparent_css('.footer-widget-area ul li a'); };
self::generate_css('.footer-widget-area ul li', 'font-family', 'footer_widget_menu_font_family');
self::font_css('.footer-widget-area ul li', 'footer_widget_menu_font');
self::generate_css('.footer-widget-area ul li a', 'color', 'footer_widget_menu_txt_color');
self::generate_css('.footer-widget-area ul li a', 'border-color', 'footer_widget_menu_border_color');
if(get_theme_mod('footer_widget_menu_hover_transparent_bg', $tubeaceplay_customizer_defaults['footer_widget_menu_hover_transparent_bg'])==false){ self::generate_css('.footer-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'background-color', 'footer_widget_menu_hover_bg_color'); } else { self::transparent_css('.footer-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover'); };
self::generate_css('.footer-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'color', 'footer_widget_menu_hover_txt_color');
self::generate_css('.footer-widget-area ul li:not(.current_page_item):not(.current-cat) a:hover', 'border-color', 'footer_widget_menu_hover_border_color');
if(get_theme_mod('footer_widget_menu_current_transparent_bg', $tubeaceplay_customizer_defaults['footer_widget_menu_current_transparent_bg'])==false){ self::generate_css('.footer-widget-area .current_page_item > a, .footer-widget-area .current-cat > a', 'background-color', 'footer_widget_menu_current_bg_color'); } else { self::transparent_css('.footer-widget-area .current_page_item > a, .footer-widget-area .current-cat > a'); };
self::generate_css('.footer-widget-area .current_page_item > a, .footer-widget-area .current-cat > a', 'color', 'footer_widget_menu_current_txt_color');
self::generate_css('.footer-widget-area .current_page_item > a, .footer-widget-area .current-cat > a', 'border-color', 'footer_widget_menu_current_border_color');

## Pages ##
/* Post Page */
if(  is_single() || get_theme_mod('preview_excerpt_content')=='content' ){
	if(get_theme_mod('post_page_transparent_bg', $tubeaceplay_customizer_defaults['post_page_transparent_bg'])==false){ self::generate_css('#post', 'background-color', 'post_page_bg_color'); } else { self::transparent_css('#post'); };
	self::generate_css('#post', 'font-family', 'post_page_font_family');
	self::font_css('#post', 'post_page_font');
	self::generate_css('#post', 'color', 'post_page_txt_color');
	self::generate_css('#post :not(.post-page-tags, .post-page-category, .post-page-performers, blockquote) a', 'color', 'post_page_link_color');
	self::generate_css('#post', 'border-color', 'post_page_border_color');
	self::generate_css('h1#post-title', 'font-family', 'post_page_title_font_family');
	self::font_css('h1#post-title', 'post_page_title_font');
	self::generate_css('h1#post-title', 'color', 'post_page_title_txt_color');
	if(get_theme_mod('post_page_blockquote_transparent_bg', $tubeaceplay_customizer_defaults['post_page_blockquote_transparent_bg'])==false){ self::generate_css('blockquote', 'background-color', 'post_page_blockquote_bg_color'); } else { self::transparent_css('blockquote'); };
	self::generate_css('blockquote', 'font-family', 'post_page_blockquote_font_family');
	self::font_css('blockquote', 'post_page_blockquote_font');
	self::generate_css('blockquote', 'color', 'post_page_blockquote_txt_color');
	self::blockquote_css('blockquote a', 'color', 'post_page_blockquote_link_color');
	self::generate_css('blockquote', 'border-color', 'post_page_blockquote_border_color');
	self::generate_css('#post hr', 'border-color', 'post_page_hr_color');
	self::generate_css('.post-page-tags', 'color', 'post_page_tags_label_color');
	self::generate_css('.post-page-tags > a', 'color', 'post_page_tags_txt_color');
	self::generate_css('.post-page-tags', 'font-family', 'post_page_tags_font_family');
	self::font_css('.post-page-tags', 'post_page_tags_font');
	if(get_theme_mod('post_page_tags_transparent_bg', $tubeaceplay_customizer_defaults['post_page_tags_transparent_bg'])==false){ self::generate_css('.post-page-tags > a', 'background-color', 'post_page_tags_bg_color'); } else { self::transparent_css('.post-page-tags > a'); };
	self::generate_css('.post-page-tags > a', 'border-color', 'post_page_tags_border_color');
	self::generate_css('.post-page-category', 'color', 'post_page_category_label_color');
	self::generate_css('.post-page-category > a', 'color', 'post_page_category_txt_color');
	self::generate_css('.post-page-category', 'font-family', 'post_page_category_font_family');
	self::font_css('.post-page-category', 'post_page_category_font');
	if(get_theme_mod('post_page_category_transparent_bg', $tubeaceplay_customizer_defaults['post_page_category_transparent_bg'])==false){ self::generate_css('.post-page-category > a', 'background-color', 'post_page_category_bg_color'); } else { self::transparent_css('.post-page-category > a'); };
	self::generate_css('.post-page-category > a', 'border-color', 'post_page_category_border_color');
	self::generate_css('.post-page-performers', 'color', 'post_page_performers_label_color');
	self::generate_css('.post-page-performers > a', 'color', 'post_page_performers_txt_color');
	self::generate_css('.post-page-performers', 'font-family', 'post_page_performers_font_family');
	self::font_css('.post-page-performers', 'post_page_performers_font');
	if(get_theme_mod('post_page_performers_transparent_bg', $tubeaceplay_customizer_defaults['post_page_performers_transparent_bg'])==false){ self::generate_css('.post-page-performers > a', 'background-color', 'post_page_performers_bg_color'); } else { self::transparent_css('.post-page-performers > a'); };
	self::generate_css('.post-page-performers > a', 'border-color', 'post_page_performers_border_color');
	self::generate_css('#post time', 'color', 'post_page_date_txt_color');
	self::generate_css('#post a.author-link, .author', 'color', 'post_page_author_txt_color');	

	self::generate_css('#post-page-related-title', 'color', 'post_page_related_label_color');
	self::generate_css('#post-page-related-title', 'font-family', 'post_page_related_font_family');
	self::font_css('#post-page-related-title', 'post_page_related_font');

}
/* Page Page */
if( is_page() ){
	if(get_theme_mod('page_page_transparent_bg', $tubeaceplay_customizer_defaults['page_page_transparent_bg'])==false){ self::generate_css('#page', 'background-color', 'page_page_bg_color'); } else { self::transparent_css('#page'); };
	self::generate_css('#page', 'font-family', 'page_page_font_family');
	self::font_css('#page', 'page_page_font');
	self::generate_css('#page', 'color', 'page_page_txt_color');
	self::generate_css('#page a', 'color', 'page_page_link_color');
	self::generate_css('#page', 'border-color', 'page_page_border_color');
	self::generate_css('h1#page-title', 'font-family', 'page_page_title_font_family');
	self::font_css('h1#page-title', 'page_page_title_font');
	self::generate_css('h1#page-title', 'color', 'page_page_title_txt_color');
}
/* Archive Page */
if ( is_archive() ) {
	self::generate_css('h1#archive-title', 'font-family', 'archive_page_title_font_family');
	self::font_css('h1#archive-title', 'archive_page_title_font');
	self::generate_css('h1#archive-title', 'color', 'archive_page_title_txt_color');
	self::generate_css('#archives-monthly-title', 'color', 'archive_page_monthly_list_title_color');
	self::generate_css('#archives-monthly a', 'color', 'archive_page_monthly_list_link_color');
}
/* Attachment Page */
if ( is_attachment() ) {
	if(get_theme_mod('attachment_page_transparent_bg', $tubeaceplay_customizer_defaults['attachment_page_transparent_bg'])==false){ self::generate_css('#attachment', 'background-color', 'attachment_page_bg_color'); } else { self::transparent_css('#attachment'); };
	self::generate_css('#attachment', 'font-family', 'attachment_page_font_family');
	self::font_css('#attachment', 'attachment_page_font');
	self::generate_css('#attachment', 'color', 'attachment_page_txt_color');
	self::generate_css('#attachment a', 'color', 'attachment_page_link_color');
	self::generate_css('#attachment', 'border-color', 'attachment_page_border_color');
	self::generate_css('h1#attachment-title', 'font-family', 'attachment_page_title_font_family');
	self::font_css('h1#attachment-title', 'attachment_page_title_font');
	self::generate_css('h1#attachment-title', 'color', 'attachment_page_title_txt_color');
	self::generate_css('#attachment time', 'color', 'attachment_page_date_txt_color');
	self::generate_css('#attachment a.author-link, .author', 'color', 'attachment_page_author_txt_color');
}
/* Author Page */
if ( is_author() ) {
	if(get_theme_mod('author_page_content_transparent_bg', $tubeaceplay_customizer_defaults['author_page_content_transparent_bg'])==false){ self::generate_css('div#author', 'background-color', 'author_page_content_bg_color'); } else { self::transparent_css('div#author'); };
	self::generate_css('#author-meta', 'font-family', 'author_page_font_family');
	self::font_css('#author-meta', 'author_page_font');
	self::generate_css('#author-meta', 'color', 'author_page_content_txt_color');
	self::generate_css('#author-meta a', 'color', 'author_page_content_link_color');
	self::generate_css('div#author', 'border-color', 'author_page_content_border_color');
	self::generate_css('h1#author-title', 'font-family', 'author_page_title_font_family');
	self::font_css('h1#author-title', 'author_page_title_font');
	self::generate_css('h1#author-title', 'color', 'author_page_title_txt_color');
}
/* Category Page */
if ( is_category() ) {
	self::generate_css('h1#category-name', 'font-family', 'category_page_title_font_family');
	self::font_css('h1#category-name', 'category_page_title_font');
	self::generate_css('h1#category-name', 'color', 'category_page_title_txt_color');
}
/* Tag Page */
if ( is_tag() ) {
	self::generate_css('h1#tag-name', 'font-family', 'tag_page_title_font_family');
	self::font_css('h1#tag-name', 'tag_page_title_font');
	self::generate_css('h1#tag-name', 'color', 'tag_page_title_txt_color');
}
/* Taxonomy Page */

	self::generate_css('h1#taxonomy-name', 'font-family', 'taxonomy_page_title_font_family');
	self::font_css('h1#taxonomy-name', 'taxonomy_page_title_font');
	self::generate_css('h1#taxonomy-name', 'color', 'taxonomy_page_title_txt_color');

/* Search Page */
if ( is_search() ) {
	self::generate_css('h1#search-title', 'font-family', 'search_page_title_font_family');
	self::font_css('h1#search-title', 'search_page_title_font');
	self::generate_css('h1#search-title', 'color', 'search_page_title_txt_color');
	if(get_theme_mod('search_page_transparent_bg', $tubeaceplay_customizer_defaults['search_page_transparent_bg'])==false){ self::generate_css('#search-error-content', 'background-color', 'search_page_bg_color'); } else { self::transparent_css('#search-error-content'); };
	self::generate_css('#search-error-content', 'font-family', 'search_page_font_family');
	self::font_css('#search-error-content', 'search_page_font');
	self::generate_css('#search-error-content', 'color', 'search_page_txt_color');
	self::generate_css('#search-error-content a', 'color', 'search_page_link_color');
	self::generate_css('#search-error-content', 'border-color', 'search_page_border_color');
}
/* 404 Page */
if( is_404() ){
	self::generate_css('h1#page-404-title', 'font-family', 'page_404_title_font_family');
	self::font_css('h1#page-404-title', 'page_404_title_font');
	self::generate_css('h1#page-404-title', 'color', 'page_404_title_txt_color');
	if(get_theme_mod('page_404_transparent_bg', $tubeaceplay_customizer_defaults['page_404_transparent_bg'])==false){ self::generate_css('#page-404', 'background-color', 'page_404_bg_color'); } else { self::transparent_css('#page-404'); };
	self::generate_css('#page-404', 'font-family', 'page_404_font_family');
	self::font_css('#page-404', 'page_404_font');
	self::generate_css('#page-404', 'color', 'page_404_txt_color');
	self::generate_css('#page-404 a', 'color', 'page_404_link_color');
	self::generate_css('#page-404', 'border-color', 'page_404_border_color');
}
/* Calendar Widget */
self::generate_css('#wp-calendar tbody td', 'background-color', 'calendar_bg_color');
self::generate_css('#wp-calendar tbody td:hover', 'background-color', 'calendar_hover_bg_color');
self::generate_css('#wp-calendar', 'font-family', 'calendar_font_family');
self::font_css('#wp-calendar', 'calendar_font');
self::generate_css('#wp-calendar caption', 'color', 'calendar_month_color');
self::generate_css('#wp-calendar thead', 'color', 'calendar_days_color');
self::generate_css('#wp-calendar tbody td', 'border-color', 'calendar_border_color');
self::generate_css('#wp-calendar tbody', 'color', 'calendar_txt_color');
self::generate_css('#wp-calendar tbody a', 'color', 'calendar_link_color');
self::generate_css('#wp-calendar tfoot tr a', 'color', 'calendar_pagination_color');
/* Tag Cloud Widget */
self::generate_css('.tagcloud', 'background-color', 'tag_cloud_bg_color');
self::generate_css('.tagcloud', 'font-family', 'tag_cloud_font_family');
self::generate_css('.tagcloud', 'border-color', 'tag_cloud_border_color');
self::generate_css('.tagcloud a', 'color', 'tag_cloud_item_txt_color');
self::generate_css('.tagcloud a', 'background-color', 'tag_cloud_item_bg_color');
self::generate_css('.tagcloud a', 'border-color', 'tag_cloud_item_border_color');
